version: '3.8'

services:
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Merei04977773@
      POSTGRES_DB: shop
    ports:
      - "5434:5432"
