version: '3.8'

services:
  golang:
    build: .
    container_name: kazakTeam
    ports:
      - "8080:8080"
    depends_on:
      - pgdb
    volumes:
      - C:/Users/Merei/Desktop/merei codes/Golang/final project/backend/kazakTeam-backend:/app
    networks:
      - app-network
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Merei04977773@
      POSTGRES_DB: kazakTeam
    ports:
      - "5434:5432"
    networks:
      - app-network

networks:
  app-network:
